<?xml version="1.0"?>
<!DOCTYPE issues [
    <!ELEMENT issues (issue*)>
    <!ATTLIST issues burpVersion CDATA "">
    <!ATTLIST issues exportTime CDATA "">
    <!ELEMENT issue (serialNumber, type, name, host, path, location, severity, confidence, issueBackground?, remediationBackground?, issueDetail?, issueDetailItems?, remediationDetail?, requestresponse*)>
    <!ELEMENT serialNumber (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT host (#PCDATA)>
    <!ATTLIST host ip CDATA "">
    <!ELEMENT path (#PCDATA)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT severity (#PCDATA)>
    <!ELEMENT confidence (#PCDATA)>
    <!ELEMENT issueBackground (#PCDATA)>
    <!ELEMENT remediationBackground (#PCDATA)>
    <!ELEMENT issueDetail (#PCDATA)>
    <!ELEMENT issueDetailItems (issueDetailItem*)>
    <!ELEMENT issueDetailItem (#PCDATA)>
    <!ELEMENT remediationDetail (#PCDATA)>
    <!ELEMENT requestresponse (request?, response?, responseRedirected?)>
    <!ELEMENT request (#PCDATA)>
    <!ATTLIST request method CDATA "">
    <!ATTLIST request base64 (true|false) "false">
    <!ELEMENT response (#PCDATA)>
    <!ATTLIST response base64 (true|false) "false">
    <!ELEMENT responseRedirected (#PCDATA)>
    ]>
<issues burpVersion="1.6.12" exportTime="Mon Mar 23 15:59:35 CET 2015">
  <issue>
    <serialNumber>5972985483239353344</serialNumber>
    <type>5245344</type>
    <name>Frameable response (potential Clickjacking)</name>
    <host ip="172.22.8.13">http://vm-stapp-95:20756</host>
    <path><![CDATA[/]]></path>
    <location><![CDATA[/]]></location>
    <severity>Information</severity>
    <confidence>Firm</confidence>
    <issueBackground><![CDATA[It might be possible for a web page controlled by an attacker to load the content of this response within an iframe on the attacker's page. This may enable a "clickjacking" attack, in which the attacker's page overlays the target application's interface with a different interface provided by the attacker. By inducing victim users to perform actions such as mouse clicks and keystrokes, the attacker can cause them to unwittingly carry out actions within the application that is being targeted. This technique allows the attacker to circumvent defenses against cross-site request forgery, and may result in unauthorized actions.<br><br>Note that this issue is being reported because the application's response does not set a suitable <b>X-Frame-Options</b> header in order to prevent framing attacks. Some applications attempt to prevent these attacks from within the HTML page itself, using "framebusting" code. However, this type of defense is normally ineffective and can usually be circumvented by a skilled attacker.]]></issueBackground>
    <remediationBackground><![CDATA[You should review the application functions that are accessible from within the response, and determine whether they can be used by application users to perform any sensitive actions within the application. If so, then a framing attack targeting this response may result in unauthorized actions.<br><br>To effectively prevent framing attacks, the application should return a response header with the name <b>X-Frame-Options</b> and the value <b>DENY</b> to prevent framing altogether, or the value <b>SAMEORIGIN</b> to allow framing only by pages on the same origin as the response itself.]]></remediationBackground>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC8gSFRUUC8xLjENCkhvc3Q6IHZtLXN0YXBwLTk1OjIwNzU2DQpBY2NlcHQ6ICovKg0KQWNjZXB0LUxhbmd1YWdlOiBlbg0KVXNlci1BZ2VudDogTW96aWxsYS81LjAgKGNvbXBhdGlibGU7IE1TSUUgOS4wOyBXaW5kb3dzIE5UIDYuMTsgV2luNjQ7IHg2NDsgVHJpZGVudC81LjApDQpDb25uZWN0aW9uOiBjbG9zZQ0KDQo=]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBNb24sIDIzIE1hciAyMDE1IDE0OjU3OjQzIEdNVA0KTGFzdC1Nb2RpZmllZDogVGh1LCAxOSBNYXIgMjAxNSAxNjozNzoxMCBHTVQNCkNvbnRlbnQtVHlwZTogdGV4dC9odG1sO2NoYXJzZXQ9dXRmLTgNCkNvbnRlbnQtTGVuZ3RoOiAxMzA0DQpDb25uZWN0aW9uOiBjbG9zZQ0KU2VydmVyOiBKZXR0eSg5LjIuOS52MjAxNTAyMjQpDQoNCjwhRE9DVFlQRSBodG1sPjwhLS1baWYgbHQgSUUgN10+IDxodG1sIGxhbmc9ImVuIiBjbGFzcz0ibm8tanMgbHQtaWU5IGx0LWllOCBsdC1pZTciPiA8IVtlbmRpZl0tLT48IS0tW2lmIElFIDddPiA8aHRtbCBsYW5nPSJlbiIgY2xhc3M9Im5vLWpzIGx0LWllOSBsdC1pZTgiPiA8IVtlbmRpZl0tLT48IS0tW2lmIElFIDhdPiA8aHRtbCBsYW5nPSJlbiIgY2xhc3M9Im5vLWpzIGx0LWllOSI+IDwhW2VuZGlmXS0tPjwhLS1baWYgZ3QgSUUgOF0+PCEtLT4gPGh0bWwgbGFuZz1lbiBjbGFzcz1uby1qcz4gPCEtLTwhW2VuZGlmXS0tPiA8aGVhZD4gPG1ldGEgY2hhcnNldD11dGYtOD4gPG1ldGEgaHR0cC1lcXVpdj1YLVVBLUNvbXBhdGlibGUgY29udGVudD0iSUU9ZWRnZSI+IDxtZXRhIG5hbWU9dmlld3BvcnQgY29udGVudD0id2lkdGg9ZGV2aWNlLXdpZHRoLGluaXRpYWwtc2NhbGU9MSI+IDx0aXRsZT5JbnZvaWNlIFNvbHV0aW9ucyBUcmFuc2FjdGlvbiBSZWdpc3RlcjwvdGl0bGU+IDwhLS0gUGxhY2UgZmF2aWNvbi5pY28gYW5kIGFwcGxlLXRvdWNoLWljb24ucG5nIGluIHRoZSByb290IGRpcmVjdG9yeSAtLT4gPGxpbmsgcmVsPXN0eWxlc2hlZXQgaHJlZj1hc3NldHMvc3R5bGVzL2ViMmQxZmM0LnZlbmRvci5jc3M+IDxsaW5rIHJlbD1zdHlsZXNoZWV0IGhyZWY9YXNzZXRzL3N0eWxlcy81ODBiMjJiZC5tYWluLmNzcz4gPGxpbmsgcmVsPXN0eWxlc2hlZXQgaHJlZj0vL21heGNkbi5ib290c3RyYXBjZG4uY29tL2ZvbnQtYXdlc29tZS80LjMuMC9jc3MvZm9udC1hd2Vzb21lLm1pbi5jc3M+IDwvaGVhZD4gPGJvZHkgbmctYXBwPXRyYW5zUmVnQXBwPiA8IS0tW2lmIGx0IElFIDddPgo8cCBjbGFzcz0iYnJvd3NlaGFwcHkiPllvdSBhcmUgdXNpbmcgYW4gPHN0cm9uZz5vdXRkYXRlZDwvc3Ryb25nPiBicm93c2VyLiBQbGVhc2UgPGEgaHJlZj0iaHR0cDovL2Jyb3dzZWhhcHB5LmNvbS8iPnVwZ3JhZGUKICB5b3VyIGJyb3dzZXI8L2E+IHRvIGltcHJvdmUgeW91ciBleHBlcmllbmNlLjwvcD4KPCFbZW5kaWZdLS0+IDxkaXYgdWktdmlldz1uYXZiYXIgbmctY2xvYWs9IiI+PC9kaXY+IDxkaXYgY2xhc3M9Y29udGFpbmVyPiA8ZGl2IGNsYXNzPWNvbC1tZC0xNiByb2xlPW1haW4+IDxkaXYgdWktdmlldz1jb250ZW50PjwvZGl2PiA8L2Rpdj4gPC9kaXY+IDxkaXYgdWktdmlldz1mb290ZXI+PC9kaXY+IDxzY3JpcHQgc3JjPXNjcmlwdHMvODkwZjNjZDkudmVuZG9yLmpzPjwvc2NyaXB0PiA8c2NyaXB0IHNyYz1zY3JpcHRzLzg0YzMwZTM1LmFwcC5qcz48L3NjcmlwdD4gPC9ib2R5PiA8L2h0bWw+]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>5248710575388354560</serialNumber>
    <type>5245440</type>
    <name>TRACE method is enabled</name>
    <host ip="172.22.8.13">http://vm-stapp-95:20756</host>
    <path><![CDATA[/]]></path>
    <location><![CDATA[/]]></location>
    <severity>Information</severity>
    <confidence>Certain</confidence>
    <issueBackground><![CDATA[The TRACE method is designed for diagnostic purposes. If enabled, the web server will respond to requests which use the TRACE method by echoing in its response the exact request which was received.<br><br>Although this behavior is apparently harmless in itself, it can sometimes be leveraged to support attacks against other application users. If an attacker can find a way of causing a user to make a TRACE request, and can retrieve the response to that request, then the attacker will be able to capture any sensitive data which is included in the request by the user's browser, for example session cookies or credentials for platform-level authentication. This may exacerbate the impact of other vulnerabilities, such as cross-site scripting.]]></issueBackground>
    <remediationBackground><![CDATA[The TRACE method should be disabled on the web server.]]></remediationBackground>
    <requestresponse>
      <request method="TRACE" base64="true"><![CDATA[VFJBQ0UgLyBIVFRQLzEuMA0KSG9zdDogdm0tc3RhcHAtOTUNCkNvb2tpZTogNGM3YjIzZDE5MA0KDQo=]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBNb24sIDIzIE1hciAyMDE1IDE0OjU3OjQ0IEdNVA0KQ29udGVudC1UeXBlOiBtZXNzYWdlL2h0dHA7IGNoYXJzZXQ9VVRGLTgNCkNvbnRlbnQtTGVuZ3RoOiA3Mg0KU2VydmVyOiBKZXR0eSg5LjIuOS52MjAxNTAyMjQpDQoNClRSQUNFIC9kaXN0L2luZGV4Lmh0bWwgSFRUUC8xLjANCkNvb2tpZTogNGM3YjIzZDE5MA0KSG9zdDogdm0tc3RhcHAtOTUNCg==]]></response>
      <responseRedirected>false</responseRedirected>
    </requestresponse>
  </issue>
  <issue>
    <serialNumber>1057040137878520832</serialNumber>
    <type>6291632</type>
    <name>Source code disclosure</name>
    <host ip="172.22.8.13">http://vm-stapp-95:20756</host>
    <path><![CDATA[/scripts/890f3cd9.vendor.js]]></path>
    <location><![CDATA[/scripts/890f3cd9.vendor.js]]></location>
    <severity>Low</severity>
    <confidence>Tentative</confidence>
    <issueBackground><![CDATA[Server-side source code may contain sensitive information which can help an attacker formulate attacks against the application.]]></issueBackground>
    <remediationBackground><![CDATA[Server-side source code is normally disclosed to clients as a result of typographical errors in scripts or because of misconfiguration, such as failing to grant executable permissions to a script or directory. You should review the cause of the code disclosure and prevent it from happening.]]></remediationBackground>
    <issueDetail><![CDATA[The application appears to disclose some server-side source code written in PHP and ASP.]]></issueDetail>
    <requestresponse>
      <request method="GET" base64="true"><![CDATA[R0VUIC9zY3JpcHRzLzg5MGYzY2Q5LnZlbmRvci5qcyBIVFRQLzEuMQ0KSG9zdDogdm0tc3RhcHAtOTU6MjA3NTYNCkFjY2VwdDogKi8qDQpBY2NlcHQtTGFuZ3VhZ2U6IGVuDQpVc2VyLUFnZW50OiBNb3ppbGxhLzUuMCAoY29tcGF0aWJsZTsgTVNJRSA5LjA7IFdpbmRvd3MgTlQgNi4xOyBXaW42NDsgeDY0OyBUcmlkZW50LzUuMCkNCkNvbm5lY3Rpb246IGNsb3NlDQpSZWZlcmVyOiBodHRwOi8vdm0tc3RhcHAtOTU6MjA3NTYvDQoNCg==]]></request>
      <response base64="true"><![CDATA[SFRUUC8xLjEgMjAwIE9LDQpEYXRlOiBNb24sIDIzIE1hciAyMDE1IDE0OjU3OjUxIEdNVA0KQ2FjaGUtQ29udHJvbDogbWF4LWFnZT0yNjc4NDAwMDAwLCBwdWJsaWMNClByYWdtYTogY2FjaGUNCkV4cGlyZXM6IFRodSwgMjMgQXByIDIwMTUgMTQ6NTc6NTEgR01UDQpMYXN0LU1vZGlmaWVkOiBUaHUsIDE5IE1hciAyMDE1IDE2OjQyOjA3IEdNVA0KQ29udGVudC1UeXBlOiBhcHBsaWNhdGlvbi9qYXZhc2NyaXB0OyBjaGFyc2V0PVVURi04DQpDb250ZW50LUxlbmd0aDogNzQ0MDkzDQpDb25uZWN0aW9uOiBjbG9zZQ0KU2VydmVyOiBKZXR0eSg5LjIuOS52MjAxNTAyMjQpDQoNCndpbmRvdy5Nb2Rlcm5penI9ZnVuY3Rpb24oYSxiLGMpe2Z1bmN0aW9uIGQoYSl7dC5jc3NUZXh0PWF9ZnVuY3Rpb24gZShhLGIpe3JldHVybiBkKHguam9pbihhKyI7IikrKGJ8fCIiKSl9ZnVuY3Rpb24gZihhLGIpe3JldHVybiB0eXBlb2YgYT09PWJ9ZnVuY3Rpb24gZyhhLGIpe3JldHVybiEhfigiIithKS5pbmRleE9mKGIpfWZ1bmN0aW9uIGgoYSxiKXtmb3IodmFyIGQgaW4gYSl7dmFyIGU9YVtkXTtpZighZyhlLCItIikmJnRbZV0hPT1jKXJldHVybiJwZngiPT1iP2U6ITB9cmV0dXJuITF9ZnVuY3Rpb24gaShhLGIsZCl7Zm9yKHZhciBlIGluIGEpe3ZhciBnPWJbYVtlXV07aWYoZyE9PWMpcmV0dXJuIGQ9PT0hMT9hW2VdOmYoZywiZnVuY3Rpb24iKT9nLmJpbmQoZHx8Yik6Z31yZXR1cm4hMX1mdW5jdGlvbiBqKGEsYixjKXt2YXIgZD1hLmNoYXJBdCgwKS50b1VwcGVyQ2FzZSgpK2Euc2xpY2UoMSksZT0oYSsiICIrei5qb2luKGQrIiAiKStkKS5zcGxpdCgiICIpO3JldHVybiBmKGIsInN0cmluZyIpfHxmKGIsInVuZGVmaW5lZCIpP2goZSxiKTooZT0oYSsiICIrQS5qb2luKGQrIiAiKStkKS5zcGxpdCgiICIpLGkoZSxiLGMpKX1mdW5jdGlvbiBrKCl7by5pbnB1dD1mdW5jdGlvbihjKXtmb3IodmFyIGQ9MCxlPWMubGVuZ3RoO2U+ZDtkKyspRVtjW2RdXT0hIShjW2RdaW4gdSk7cmV0dXJuIEUubGlzdCYmKEUubGlzdD0hKCFiLmNyZWF0ZUVsZW1lbnQoImRhdGFsaXN0Iil8fCFhLkhUTUxEYXRhTGlzdEVsZW1lbnQpKSxFfSgiYXV0b2NvbXBsZXRlIGF1dG9mb2N1cyBsaXN0IHBsYWNlaG9sZGVyIG1heCBtaW4gbXVsdGlwbGUgcGF0dGVybiByZXF1aXJlZCBzdGVwIi5zcGxpdCgiICIpKSxvLmlucHV0dHlwZXM9ZnVuY3Rpb24oYSl7Zm9yKHZhciBkLGUsZixnPTAsaD1hLmxlbmd0aDtoPmc7ZysrKXUuc2V0QXR0cmlidXRlKCJ0eXBlIixlPWFbZ10pLGQ9InRleHQiIT09dS50eXBlLGQmJih1LnZhbHVlPXYsdS5zdHlsZS5jc3NUZXh0PSJwb3NpdGlvbjphYnNvbHV0ZTt2aXNpYmlsaXR5OmhpZGRlbjsiLC9ecmFuZ2UkLy50ZXN0KGUpJiZ1LnN0eWxlLldlYmtpdEFwcGVhcmFuY2UhPT1jPyhxLmFwcGVuZENoaWxkKHUpLGY9Yi5kZWZhdWx0VmlldyxkPWYuZ2V0Q29tcHV0ZWRTdHlsZSYmInRleHRmaWVsZCIhPT1mLmdldENvbXB1dGVkU3R5bGUodSxudWxsKS5XZWJraXRBcHBlYXJhbmNlJiYwIT09dS5vZmZzZXRIZWlnaHQscS5yZW1vdmVDaGlsZCh1KSk6L14oc2VhcmNofHRlbCkkLy50ZXN0KGUpfHwoZD0vXih1cmx8ZW1haWwpJC8udGVzdChlKT91LmNoZWNrVmFsaWRpdHkmJnUuY2hlY2tWYWxpZGl0eSgpPT09ITE6dS52YWx1ZSE9dikpLERbYVtnXV09ISFkO3JldHVybiBEfSgic2VhcmNoIHRlbCB1cmwgZW1haWwgZGF0ZXRpbWUgZGF0ZSBtb250aCB3ZWVrIHRpbWUgZGF0ZXRpbWUtbG9jYWwgbnVtYmVyIHJhbmdlIGNvbG9yIi5zcGxpdCgiICIpKX12YXIgbCxtLG49IjIuOC4zIixvPXt9LHA9ITAscT1iLmRvY3VtZW50RWxlbWVudCxyPSJtb2Rlcm5penIiLHM9Yi5jcmVhdGVFbGVtZW50KHIpLHQ9cy5zdHlsZSx1PWIuY3JlYXRlRWxlbWVudCgiaW5wdXQiKSx2PSI6KSIsdz17fS50b1N0cmluZyx4PSIgLXdlYmtpdC0gLW1vei0gLW8tIC1tcy0gIi5zcGxpdCgiICIpLHk9IldlYmtpdCBNb3ogTyBtcyIsej15LnNwbGl0KCIgIiksQT15LnRvTG93ZXJDYXNlKCkuc3BsaXQoIiAiKSxCPXtzdmc6Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIn0sQz17fSxEPXt9LEU9e30sRj1bXSxHPUYuc2xpY2UsSD1mdW5jdGlvbihhLGMsZCxlKXt2YXIgZixnLGgsaSxqPWIuY3JlYXRlRWxlbWVudCgiZGl2Iiksaz1iLmJvZHksbD1rfHxiLmNyZWF0ZUVsZW1lbnQoImJvZHkiKTtpZihwYXJzZUludChkLDEwKSlmb3IoO2QtLTspaD1iLmNyZWF0ZUVsZW1lbnQoImRpdiIpLGguaWQ9ZT9lW2RdOnIrKGQrMSksai5hcHBlbmRDaGlsZChoKTtyZXR1cm4gZj1bIiYjMTczOyIsJzxzdHlsZSBpZD0icycsciwnIj4nLGEsIjwvc3R5bGU+Il0uam9pbigiIiksai5pZD1yLChrP2o6bCkuaW5uZXJIVE1MKz1mLGwuYXBwZW5kQ2hpbGQoaiksa3x8KGwuc3R5bGUuYmFja2dyb3VuZD0iIixsLnN0eWxlLm92ZXJmbG93PSJoaWRkZW4iLGk9cS5zdHlsZS5vdmVyZmxvdyxxLnN0eWxlLm92ZXJmbG93PSJoaWRkZW4iLHEuYXBwZW5kQ2hpbGQobCkpLGc9YyhqLGEpLGs/ai5wYXJlbnROb2RlLnJlbW92ZUNoaWxkKGopOihsLnBhcmVudE5vZGUucmVtb3ZlQ2hpbGQobCkscS5zdHlsZS5vdmVyZmxvdz1pKSwhIWd9LEk9ZnVuY3Rpb24oYil7dmFyIGM9YS5tYXRjaE1lZGlhfHxhLm1zTWF0Y2hNZWRpYTtpZihjKXJldHVybiBjKGIpJiZjKGIpLm1hdGNoZXN8fCExO3ZhciBkO3JldHVybiBIKCJAbWVkaWEgIitiKyIgeyAjIityKyIgeyBwb3NpdGlvbjogYWJzb2x1dGU7IH0gfSIsZnVuY3Rpb24oYil7ZD0iYWJzb2x1dGUiPT0oYS5nZXRDb21wdXRlZFN0eWxlP2dldENvbXB1dGVkU3R5bGUoYixudWxsKTpiLmN1cnJlbnRTdHlsZSkucG9zaXRpb259KSxkfSxKPWZ1bmN0aW9uKCl7ZnVuY3Rpb24gYShhLGUpe2U9ZXx8Yi5jcmVhdGVFbGVtZW50KGRbYV18fCJkaXYiKSxhPSJvbiIrYTt2YXIgZz1hIGluIGU7cmV0dXJuIGd8fChlLnNldEF0dHJpYnV0ZXx8KGU9Yi5jcmVhdGVFbGVtZW50KCJkaXYiKSksZS5zZXRBdHRyaWJ1dGUmJmUucmVtb3ZlQXR0cmlidXRlJiYoZS5zZXRBdHRyaWJ1dGUoYSwiIiksZz1mKGVbYV0sImZ1bmN0aW9uIiksZihlW2FdLCJ1bmRlZmluZWQiKXx8KGVbYV09YyksZS5yZW1vdmVBdHRyaWJ1dGUoYSkpKSxlPW51bGwsZ312YXIgZD17c2VsZWN0OiJpbnB1dCIsY2hhbmdlOiJpbnB1dCIsc3VibWl0OiJmb3JtIixyZXNldDoiZm9ybSIsZXJyb3I6ImltZyIsbG9hZDoiaW1nIixhYm9ydDoiaW1nIn07cmV0dXJuIGF9KCksSz17fS5oYXNPd25Qcm9wZXJ0eTttPWYoSywidW5kZWZpbmVkIil8fGYoSy5jYWxsLCJ1bmRlZmluZWQiKT9mdW5jdGlvbihhLGIpe3JldHVybiBiIGluIGEmJmYoYS5jb25zdHJ1Y3Rvci5wcm90b3R5cGVbYl0sInVuZGVmaW5lZCIpfTpmdW5jdGlvbihhLGIpe3JldHVybiBLLmNhbGwoYSxiKX0sRnVuY3Rpb24ucHJvdG90eXBlLmJpbmR8fChGdW5jdGlvbi5wcm90b3R5cGUuYmluZD1mdW5jdGlvbihhKXt2YXIgYj10aGlzO2lmKCJmdW5jdGlvbiIhPXR5cGVvZiBiKXRocm93IG5ldyBUeXBlRXJyb3I7dmFyIGM9Ry5jYWxsKGFyZ3VtZW50cywxKSxkPWZ1bmN0aW9uKCl7aWYodGhpcyBpbnN0YW5jZW9mIGQpe3ZhciBlPWZ1bmN0aW9uKCl7fTtlLnByb3RvdHlwZT1iLnByb3RvdHlwZTt2YXIgZj1uZXcgZSxnPWIuYXBwbHkoZixjLmNvbmNhdChHLmNhbGwoYXJndW1lbnRzKSkpO3JldHVybiBPYmplY3QoZyk9PT1nP2c6Zn1yZXR1cm4gYi5hcHBseShhLGMuY29uY2F0KEcuY2FsbChhcmd1bWVudHMpKSl9O3JldHVybiBkfSksQy5mbGV4Ym94PWZ1bmN0aW9uKCl7cmV0dXJuIGooImZsZXhXcmFwIil9LEMuZmxleGJveGxlZ2FjeT1mdW5jdGlvbigpe3JldHVybiBqKCJib3hEaXJlY3Rpb24iKX0sQy5jYW52YXM9ZnVuY3Rpb24oKXt2YXIgYT1iLmNyZWF0ZUVsZW1lbnQoImNhbnZhcyIpO3JldHVybiEoIWEuZ2V0Q29udGV4dHx8IWEuZ2V0Q29udGV4dCgiMmQiKSl9LEMuY2FudmFzdGV4dD1mdW5jdGlvbigpe3JldHVybiEoIW8uY2FudmFzfHwhZihiLmNyZWF0ZUVsZW1lbnQoImNhbnZhcyIpLmdldENvbnRleHQoIjJkIikuZmlsbFRleHQsImZ1bmN0aW9uIikpfSxDLndlYmdsPWZ1bmN0aW9uKCl7cmV0dXJuISFhLldlYkdMUmVuZGVyaW5nQ29udGV4dH0sQy50b3VjaD1mdW5jdGlvbigpe3ZhciBjO3JldHVybiJvbnRvdWNoc3RhcnQiaW4gYXx8YS5Eb2N1bWVudFRvdWNoJiZiIGluc3RhbmNlb2YgRG9jdW1lbnRUb3VjaD9jPSEwOkgoWyJAbWVkaWEgKCIseC5qb2luKCJ0b3VjaC1lbmFibGVkKSwoIiksciwiKSIsInsjbW9kZXJuaXpye3RvcDo5cHg7cG9zaXRpb246YWJzb2x1dGV9fSJdLmpvaW4oIiIpLGZ1bmN0aW9uKGEpe2M9OT09PWEub2Zmc2V0VG9wfSksY30sQy5nZW9sb2NhdGlvbj1mdW5jdGlvbigpe3JldHVybiJnZW9sb2NhdGlvbiJpbiBuYXZpZ2F0b3J9LEMucG9zdG1lc3NhZ2U9ZnVuY3Rpb24oKXtyZXR1cm4hIWEucG9zdE1lc3NhZ2V9LEMud2Vic3FsZGF0YWJhc2U9ZnVuY3Rpb24oKXtyZXR1cm4hIWEub3BlbkRhdGFiYXNlfSxDLmluZGV4ZWREQj1mdW5jdGlvbigpe3JldHVybiEhaigiaW5kZXhlZERCIixhKX0sQy5oYXNoY2hhbmdlPWZ1bmN0aW9uKCl7cmV0dXJuIEooImhhc2hjaGFuZ2UiLGEpJiYoYi5kb2N1bWVudE1vZGU9PT1jfHxiLmRvY3VtZW50TW9kZT43KX0sQy5oaXN0b3J5PWZ1bmN0aW9uKCl7cmV0dXJuISghYS5oaXN0b3J5fHwhaGlzdG9yeS5wdXNoU3RhdGUpfSxDLmRyYWdhbmRkcm9wPWZ1bmN0aW9uKCl7dmFyIGE9Yi5jcmVhdGVFbGVtZW50KCJkaXYiKTtyZXR1cm4iZHJhZ2dhYmxlImluIGF8fCJvbmRyYWdzdGFydCJpbiBhJiYib25kcm9wImluIGF9LEMud2Vic29ja2V0cz1mdW5jdGlvbigpe3JldHVybiJXZWJTb2NrZXQiaW4gYXx8Ik1veldlYlNvY2tldCJpbiBhfSxDLnJnYmE9ZnVuY3Rpb24oKXtyZXR1cm4gZCgiYmFja2dyb3VuZC1jb2xvcjpyZ2JhKDE1MCwyNTUsMTUwLC41KSIpLGcodC5iYWNrZ3JvdW5kQ29sb3IsInJnYmEiKX0sQy5oc2xhPWZ1bmN0aW9uKCl7cmV0dXJuIGQoImJhY2tncm91bmQtY29sb3I6aHNsYSgxMjAsNDAlLDEwMCUsLjUpIiksZyh0LmJhY2tncm91bmRDb2xvciwicmdiYSIpfHxnKHQuYmFja2dyb3VuZENvbG9yLCJoc2xhIil9LEMubXVsdGlwbGViZ3M9ZnVuY3Rpb24oKXtyZXR1cm4gZCgiYmFja2dyb3VuZDp1cmwoaHR0cHM6Ly8pLHVybChodHRwczovLykscmVkIHVybChodHRwczovLykiKSwvKHVybFxzKlwoLio/KXszfS8udGVzdCh0LmJhY2tncm91bmQpfSxDLmJhY2tncm91bmRzaXplPWZ1bmN0aW9uKCl7cmV0dXJuIGooImJhY2tncm91bmRTaXplIil9LEMuYm9yZGVyaW1hZ2U9ZnVuY3Rpb24oKXtyZXR1cm4gaigiYm9yZGVySW1hZ2UiKX0sQy5ib3JkZXJyYWRpdXM9ZnVuY3Rpb24oKXtyZXR1cm4gaigiYm9yZGVyUmFkaXVzIil9LEMuYm94c2hhZG93PWZ1bmN0aW9uKCl7cmV0dXJuIGooImJveFNoYWRvdyIpfSxDLnRleHRzaGFkb3c9ZnVuY3Rpb24oKXtyZXR1cm4iIj09PWIuY3JlYXRlRWxlbWVudCgiZGl2Iikuc3R5bGUudGV4dFNoYWRvd30sQy5vcGFjaXR5PWZ1bmN0aW9uKCl7cmV0dXJuIGUoIm9wYWNpdHk6LjU1IiksL14wLjU1JC8udGVzdCh0Lm9wYWNpdHkpfSxDLmNzc2FuaW1hdGlvbnM9ZnVuY3Rpb24oKXtyZXR1cm4gaigiYW5pbWF0aW9uTmFtZSIpfSxDLmNzc2NvbHVtbnM9ZnVuY3Rpb24oKXtyZXR1cm4gaigiY29sdW1uQ291bnQiKX0sQy5jc3NncmFkaWVudHM9ZnVuY3Rpb24oKXt2YXIgYT0iYmFja2dyb3VuZC1pbWFnZToiLGI9ImdyYWRpZW50KGxpbmVhcixsZWZ0IHRvcCxyaWdodCBib3R0b20sZnJvbSgjOWY5KSx0byh3aGl0ZSkpOyIsYz0ibGluZWFyLWdyYWRpZW50KGxlZnQgdG9wLCM5ZjksIHdoaXRlKTsiO3JldHVybiBkKChhKyItd2Via2l0LSAiLnNwbGl0KCIgIikuam9pbihiK2EpK3guam9pbihjK2EpKS5zbGljZSgwLC1hLmxlbmd0aCkpLGcodC5iYWNrZ3JvdW5kSW1hZ2UsImdyYWRpZW50Iil9LEMuY3NzcmVmbGVjdGlvbnM9ZnVuY3Rpb24oKXtyZXR1cm4gaigiYm94UmVmbGVjdCIpfSxDLmNzc3RyYW5zZm9ybXM9ZnVuY3Rpb24oKXtyZXR1cm4hIWooInRyYW5zZm9ybSIpfSxDLmNzc3RyYW5zZm9ybXMzZD1mdW5jdGlvbigpe3ZhciBhPSEhaigicGVyc3BlY3RpdmUiKTtyZXR1cm4gYSYmIndlYmtpdFBlcnNwZWN0aXZlImluIHEuc3R5bGUmJkgoIkBtZWRpYSAodHJhbnNmb3JtLTNkKSwoLXdlYmtpdC10cmFuc2Zvcm0tM2QpeyNtb2Rlcm5penJ7bGVmdDo5cHg7cG9zaXRpb246YWJzb2x1dGU7aGVpZ2h0OjNweDt9fSIsZnVuY3Rpb24oYil7YT05PT09Yi5vZmZzZXRMZWZ0JiYzPT09Yi5vZmZzZXRIZWlnaHR9KSxhfSxDLmNzc3RyYW5zaXRpb25zPWZ1bmN0aW9uKCl7cmV0dXJuIGooInRyYW5zaXRpb24iKX0sQy5mb250ZmFjZT1mdW5jdGlvbigpe3ZhciBhO3JldHVybiBIKCdAZm9udC1mYWNlIHtmb250LWZhbWlseToiZm9udCI7c3JjOnVybCgiaHR0cHM6Ly8iKX0nLGZ1bmN0aW9uKGMsZCl7dmFyIGU9Yi5nZXRFbGVtZW50QnlJZCgic21vZGVybml6ciIpLGY9ZS5zaGVldHx8ZS5zdHlsZVNoZWV0LGc9Zj9mLmNzc1J1bGVzJiZmLmNzc1J1bGVzWzBdP2YuY3NzUnVsZXNbMF0uY3NzVGV4dDpmLmNzc1RleHR8fCIiOiIiO2E9L3NyYy9pLnRlc3QoZykmJjA9PT1nLmluZGV4T2YoZC5zcGxpdCgiICIpWzBdKX0pLGF9LEMuZ2VuZXJhdGVkY29udGVudD1mdW5jdGlvbigpe3ZhciBhO3JldHVybiBIKFsiIyIsciwie2ZvbnQ6MC8wIGF9IyIsciwnOmFmdGVye2NvbnRlbnQ6IicsdiwnIjt2aXNpYmlsaXR5OmhpZGRlbjtmb250OjNweC8xIGF9J10uam9pbigiIiksZnVuY3Rpb24oYil7YT1iLm9mZnNldEhlaWdodD49M30pLGF9LEMudmlkZW89ZnVuY3Rpb24oKXt2YXIgYT1iLmNyZWF0ZUVsZW1lbnQoInZpZGVvIiksYz0hMTt0cnl7KGM9ISFhLmNhblBsYXlUeXBlKSYmKGM9bmV3IEJvb2xlYW4oYyksYy5vZ2c9YS5jYW5QbGF5VHlwZSgndmlkZW8vb2dnOyBjb2RlY3M9InRoZW9yYSInKS5yZXBsYWNlKC9ebm8kLywiIiksYy5oMjY0PWEuY2FuUGxheVR5cGUoJ3ZpZGVvL21wNDsgY29kZWNzPSJhdmMxLjQyRTAxRSInKS5yZXBsYWNlKC9ebm8kLywiIiksYy53ZWJtPWEuY2FuUGxheVR5cGUoJ3ZpZGVvL3dlYm07IGNvZGVjcz0idnA4LCB2b3JiaXMiJykucmVwbGFjZSgvXm5vJC8sIiIpKX1jYXRjaChkKXt9cmV0dXJuIGN9LEMuYXVkaW89ZnVuY3Rpb24oKXt2YXIgYT1iLmNyZWF0ZUVsZW1lbnQoImF1ZGlvIiksYz0hMTt0cnl7KGM9ISFhLmNhblBsYXlUeXBlKSYmKGM9bmV3IEJvb2xlYW4oYyksYy5vZ2c9YS5jYW5QbGF5VHlwZSgnYXVkaW8vb2dnOyBjb2RlY3M9InZvcmJpcyInKS5yZXBsYWNlKC9ebm8kLywiIiksYy5tcDM9YS5jYW5QbGF5VHlwZSgiYXVkaW8vbXBlZzsiKS5yZXBsYWNlKC9ebm8kLywiIiksYy53YXY9YS5jYW5QbGF5VHlwZSgnYXVkaW8vd2F2OyBjb2RlY3M9IjEiJykucmVwbGFjZSgvXm5vJC8sIiIpLGMubTRhPShhLmNhblBsYXlUeXBlKCJhdWRpby94LW00YTsiKXx8YS5jYW5QbGF5VHlwZSgiYXVkaW8vYWFjOyIpKS5yZXBsYWNlKC9ebm8kLywiIikpfWNhdGNoKGQpe31yZXR1cm4gY30sQy5sb2NhbHN0b3JhZ2U9ZnVuY3Rpb24oKXt0cnl7cmV0dXJuIGxvY2FsU3RvcmFnZS5zZXRJdGVtKHIsciksbG9jYWxTdG9yYWdlLnJlbW92ZUl0ZW0ociksITB9Y2F0Y2goYSl7cmV0dXJuITF9fSxDLnNlc3Npb25zdG9yYWdlPWZ1bmN0aW9uKCl7dHJ5e3JldHVybiBzZXNzaW9uU3RvcmFnZS5zZXRJdGVtKHIsciksc2Vzc2lvblN0b3JhZ2UucmVtb3ZlSXRlbShyKSwhMH1jYXRjaChhKXtyZXR1cm4hMX19LEMud2Vid29ya2Vycz1mdW5jdGlvbigpe3JldHVybiEhYS5Xb3JrZXJ9LEMuYXBwbGljYXRpb25jYWNoZT1mdW5jdGlvbigpe3JldHVybiEhYS5hcHBsaWNhdGlvbkNhY2hlfSxDLnN2Zz1mdW5jdGlvbigpe3JldHVybiEhYi5jcmVhdGVFbGVtZW50TlMmJiEhYi5jcmVhdGVFbGVtZW50TlMoQi5zdmcsInN2ZyIpLmNyZWF0ZVNWR1JlY3R9LEMuaW5saW5lc3ZnPWZ1bmN0aW9uKCl7dmFyIGE9Yi5jcmVhdGVFbGVtZW50KCJkaXYiKTtyZXR1cm4gYS5pbm5lckhUTUw9IjxzdmcvPiIsKGEuZmlyc3RDaGlsZCYmYS5maXJzdENoaWxkLm5hbWVzcGFjZVVSSSk9PUIuc3ZnfSxDLnNtaWw9ZnVuY3Rpb24oKXtyZXR1cm4hIWIuY3JlYXRlRWxlbWVudE5TJiYvU1ZHQW5pbWF0ZS8udGVzdCh3LmNhbGwoYi5jcmVhdGVFbGVtZW50TlMoQi5zdmcsImFuaW1hdGUiKSkpfSxDLnN2Z2NsaXBwYXRocz1mdW5jdGlvbigpe3JldHVybiEhYi5jcmVhdGVFbGVtZW50TlMmJi9TVkdDbGlwUGF0aC8udGVzdCh3LmNhbGwoYi5jcmVhdGVFbGVtZW50TlMoQi5zdmcsImNsaXBQYXRoIikpKX07Zm9yKHZhciBMIGluIEMpbShDLEwpJiYobD1MLnRvTG93ZXJDYXNlKCksb1tsXT1DW0xdKCksRi5wdXNoKChvW2xdPyIiOiJuby0iKStsKSk7cmV0dXJuIG8uaW5wdXR8fGsoKSxvLmFkZFRlc3Q9ZnVuY3Rpb24oYSxiKXtpZigib2JqZWN0Ij09dHlwZW9mIGEpZm9yKHZhciBkIGluIGEpbShhLGQpJiZvLmFkZFRlc3QoZCxhW2RdKTtlbHNle2lmKGE9YS50b0xvd2VyQ2FzZSgpLG9bYV0hPT1jKXJldHVybiBvO2I9ImZ1bmN0aW9uIj09dHlwZW9mIGI/YigpOmIsInVuZGVmaW5lZCIhPXR5cGVvZiBwJiZwJiYocS5jbGFzc05hbWUrPSIgIisoYj8iIjoibm8tIikrYSksb1thXT1ifXJldHVybiBvfSxkKCIiKSxzPXU9bnVsbCxmdW5jdGlvbihhLGIpe2Z1bmN0aW9uIGMoYSxiKXt2YXIgYz1hLmNyZWF0ZUVsZW1lbnQoInAiKSxkPWEuZ2V0RWxlbWVudHNCeVRhZ05hbWUoImhlYWQiKVswXXx8YS5kb2N1bWVudEVsZW1lbnQ7cmV0dXJuIGMuaW5uZXJIVE1MPSJ4PHN0eWxlPiIrYisiPC9zdHlsZT4iLGQuaW5zZXJ0QmVmb3JlKGMubGFzdENoaWxkLGQuZmlyc3RDaGlsZCl9ZnVuY3Rpb24gZCgpe3ZhciBhPXMuZWxlbWVudHM7cmV0dXJuInN0cmluZyI9PXR5cGVvZiBhP2Euc3BsaXQoIiAiKTphfWZ1bmN0aW9uIGUoYSl7dmFyIGI9clthW3BdXTtyZXR1cm4gYnx8KGI9e30scSsrLGFbcF09cSxyW3FdPWIpLGJ9ZnVuY3Rpb24gZihhLGMsZCl7aWYoY3x8KGM9YiksaylyZXR1cm4gYy5jcmVhdGVFbGVtZW50KGEpO2R8fChkPWUoYykpO3ZhciBmO3JldHVybiBmPWQuY2FjaGVbYV0/ZC5jYWNoZVthXS5jbG9uZU5vZGUoKTpvLnRlc3QoYSk/KGQuY2FjaGVbYV09ZC5jcmVhdGVFbGVtKGEpKS5jbG9uZU5vZGUoKTpkLmNyZWF0ZUVsZW0oYSksIWYuY2FuSGF2ZUNoaWxkcmVufHxuLnRlc3QoYSl8fGYudGFnVXJuP2Y6ZC5mcmFnLmFwcGVuZENoaWxkKGYpfWZ1bmN0aW9uIGcoYSxjKXtpZihhfHwoYT1iKSxrKXJldHVybiBhLmNyZWF0ZURvY3VtZW50RnJhZ21lbnQoKTtjPWN8fGUoYSk7Zm9yKHZhciBmPWMuZnJhZy5jbG9uZU5vZGUoKSxnPTAsaD1kKCksaT1oLmxlbmd0aDtpPmc7ZysrKWYuY3JlYXRlRWxlbWVudChoW2ddKTtyZXR1cm4gZn1mdW5jdGlvbiBoKGEsYil7Yi5jYWNoZXx8KGIuY2FjaGU9e30sYi5jcmVhdGVFbGVtPWEuY3JlYXRlRWxlbWVudCxiLmNyZWF0ZUZyYWc9YS5jcmVhdGVEb2N1bWVudEZyYWdtZW50LGIuZnJhZz1iLmNyZWF0ZUZyYWcoKSksYS5jcmVhdGVFbGVtZW50PWZ1bmN0aW9uKGMpe3JldHVybiBzLnNoaXZNZXRob2RzP2YoYyxhLGIpOmIuY3JlYXRlRWxlbShjKX0sYS5jcmVhdGVEb2N1bWVudEZyYWdtZW50PUZ1bmN0aW9uKCJoLGYiLCJyZXR1cm4gZnVuY3Rpb24oKXt2YXIgbj1mLmNsb25lTm9kZSgpLGM9bi5jcmVhdGVFbGVtZW50O2guc2hpdk1ldGhvZHMmJigiK2QoKS5qb2luKCkucmVwbGFjZSgvW1x3XC1dKy9nLGZ1bmN0aW9uKGEpe3JldHVybiBiLmNyZWF0ZUVsZW0oYSksYi5mcmFnLmNyZWF0ZUVsZW1lbnQoYSksJ2MoIicrYSsnIiknfSkrIik7cmV0dXJuIG59IikocyxiLmZyYWcpfWZ1bmN0aW9uIGkoYSl7YXx8KGE9Yik7dmFyIGQ9ZShhKTtyZXR1cm4hcy5zaGl2Q1NTfHxqfHxkLmhhc0NTU3x8KGQuaGFzQ1NTPSEhYyhhLCJhcnRpY2xlLGFzaWRlLGRpYWxvZyxmaWdjYXB0aW9uLGZpZ3VyZSxmb290ZXIsaGVhZGVyLGhncm91cCxtYWluLG5hdixzZWN0aW9ue2Rpc3BsYXk6YmxvY2t9bWFya3tiYWNrZ3JvdW5kOiNGRjA7Y29sb3I6IzAwMH10ZW1wbGF0ZXtkaXNwbGF5Om5vbmV9IikpLGt8fGgoYSxkKSxhfXZhciBqLGssbD0iMy43LjAiLG09YS5odG1sNXx8e30sbj0vXjx8Xig/OmJ1dHRvbnxtYXB8c2VsZWN0fHRleHRhcmVhfG9iamVjdHxpZnJhbWV8b3B0aW9ufG9wdGdyb3VwKSQvaSxvPS9eKD86YXxifGNvZGV8ZGl2fGZpZWxkc2V0fGgxfGgyfGgzfGg0fGg1fGg2fGl8bGFiZWx8bGl8b2x8cHxxfHNwYW58c3Ryb25nfHN0eWxlfHRhYmxlfHRib2R5fHRkfHRofHRyfHVsKSQvaSxwPSJfaHRtbDVzaGl2IixxPTAscj17fTshZnVuY3Rpb24oKXt0cnl7dmFyIGE9Yi5jcmVhdGVFbGVtZW50KCJhIik7YS5pbm5lckhUTUw9Ijx4eXo+PC94eXo+IixqPSJoaWRkZW4iaW4gYSxrPTE9PWEuY2hpbGROb2Rlcy5sZW5ndGh8fGZ1bmN0aW9uKCl7Yi5jcmVhdGVFbGVtZW50KCJhIik7dmFyIGE9Yi5jcmVhdGVEb2N1bWVudEZyYWdtZW50KCk7cmV0dXJuInVuZGVmaW5lZCI9PXR5cGVvZiBhLmNsb25lTm9kZXx8InVuZGVmaW5lZCI9PXR5cGVvZiBhLmNyZWF0ZURvY3VtZW50RnJhZ21lbnR8fCJ1bmRlZmluZWQiPT10eXBlb2YgYS5jcmVhdGVFbGVtZW50fSgpfWNhdGNoKGMpe2o9ITAsaz0hMH19KCk7dmFyIHM9e2VsZW1lbnRzOm0uZWxlbWVudHN8fCJhYmJyIGFydGljbGUgYXNpZGUgYXVkaW8gYmRpIGNhbnZhcyBkYXRhIGRhdGFsaXN0IGRldGFpbHMgZGlhbG9nIGZpZ2NhcHRpb24gZmlndXJlIGZvb3RlciBoZWFkZXIgaGdyb3VwIG1haW4gbWFyayBtZXRlciBuYXYgb3V0cHV0IHByb2dyZXNzIHNlY3Rpb24gc3VtbWFyeSB0ZW1wbGF0ZSB0aW1lIHZpZGVvIix2ZXJzaW9uOmwsc2hpdkNTUzptLnNoaXZDU1MhPT0hMSxzdXBwb3J0c1Vua25vd25FbGVtZW50czprLHNoaXZNZXRob2RzOm0uc2hpdk1ldGhvZHMhPT0hMSx0eXBlOiJkZWZhdWx0IixzaGl2RG9jdW1lbnQ6aSxjcmVhdGVFbGVtZW50OmYsY3JlYXRlRG9jdW1lbnRGcmFnbWVudDpnfTthLmh0bWw1PXMsaShiKX0odGhpcyxiKSxvLl92ZXJzaW9uPW4sby5fcHJlZml4ZXM9eCxvLl9kb21QcmVmaXhlcz1BLG8uX2Nzc29tUHJlZml4ZXM9eixvLm1xPUksby5oYXNFdmVudD1KLG8udGVzdFByb3A9ZnVuY3Rpb24oYSl7cmV0dXJuIGgoW2FdKX0sby50ZXN0QWxsUHJvcHM9aixvLnRlc3RTdHlsZXM9SCxvLnByZWZpeGVkPWZ1bmN0aW9uKGEsYixjKXtyZXR1cm4gYj9qKGEsYixjKTpqKGEsInBmeCIpfSxxLmNsYXNzTmFtZT1xLmNsYXNzTmFtZS5yZXBsYWNlKC8oXnxccyluby1qcyhcc3wkKS8sIiQxJDIiKSsocD8iIGpzICIrRi5qb2luKCIgIik6IiIpLG99KHRoaXMsdGhpcy5kb2N1bWVudCksZnVuY3Rpb24oYSxiKXsib2JqZWN0Ij09dHlwZW9mIG1vZHVsZSYmIm9iamVjdCI9PXR5cGVvZiBtb2R1bGUuZXhwb3J0cz9tb2R1bGUuZXhwb3J0cz1hLmRvY3VtZW50P2IoYSwhMCk6ZnVuY3Rpb24oYSl7aWYoIWEuZG9jdW1lbnQpdGhyb3cgbmV3IEVycm9yKCJqUXVlcnkgcmVxdWlyZXMgYSB3aW5kb3cgd2l0aCBhIGRvY3VtZW50Iik7cmV0dXJuIGIoYSl9OmIoYSl9KCJ1bmRlZmluZWQiIT10eXBlb2Ygd2luZG93P3dpbmRvdzp0aGlzLGZ1bmN0aW9uKGEsYil7ZnVuY3Rpb24gYyhhKXt2YXIgYj1hLmxlbmd0aCxjPV8udHlwZShhKTtyZXR1cm4iZnVuY3Rpb24iPT09Y3x8Xy5pc1dpbmRvdyhhKT8hMToxPT09YS5ub2RlVHlwZSYmYj8hMDoiYXJyYXkiPT09Y3x8MD09PWJ8fCJudW1iZXIiPT10eXBlb2YgYiYmYj4wJiZiLTEgaW4gYX1mdW5jdGlvbiBkKGEsYixjKXtpZihfLmlzRnVuY3Rpb24oYikpcmV0dXJuIF8uZ3JlcChhLGZ1bmN0aW9uKGEsZCl7cmV0dXJuISFiLmNhbGwoYSxkLGEpIT09Y30pO2lmKGIubm9kZVR5cGUpcmV0dXJuIF8uZ3JlcChhLGZ1bmN0aW9uKGEpe3JldHVybiBhPT09YiE9PWN9KTtpZigic3RyaW5nIj09dHlwZW9mIGIpe2lmKGhhLnRlc3QoYikpcmV0dXJuIF8uZmlsdGVyKGIsYSxjKTtiPV8uZmlsdGVyKGIsYSl9cmV0dXJuIF8uZ3JlcChhLGZ1bmN0aW9uKGEpe3JldHVybiBVLmNhbGwoYixhKT49MCE9PWN9KX1mdW5jdGlvbiBlKGEsYil7Zm9yKDsoYT1hW2JdKSYmMSE9PWEubm9kZVR5cGU7KTtyZXR1cm4gYX1mdW5jdGlvbiBmKGEpe3ZhciBiPW9hW2FdPXt9O3JldHVybiBfLmVhY2goYS5tYXRjaChuYSl8fFtdLGZ1bmN0aW9uKGEsYyl7YltjXT0hMH0pLGJ9ZnVuY3Rpb24gZygpe1oucmVtb3ZlRXZlbnRMaXN0ZW5lcigiRE9NQ29udGVudExvYWRlZCIsZywhMSksYS5yZW1vdmVFdmVudExpc3RlbmVyKCJsb2FkIixnLCExKSxfLnJlYWR5KCl9ZnVuY3Rpb24gaCgpe09iamVjdC5kZWZpbmVQcm9wZXJ0eSh0aGlzLmNhY2hlPXt9LDAse2dldDpmdW5jdGlvbigpe3JldHVybnt9fX0pLHRoaXMuZXhwYW5kbz1fLmV4cGFuZG8raC51aWQrK31mdW5jdGlvbiBpKGEsYixjKXt2YXIgZDtpZih2b2lkIDA9PT1jJiYxPT09YS5ub2RlVHlwZSlpZihkPSJkYXRhLSIrYi5yZXBsYWNlKHVhLCItJDEiKS50b0xvd2VyQ2FzZSgpLGM9YS5nZXRBdHRyaWJ1dGUoZCksInN0cmluZyI9PXR5cGVvZiBjKXt0cnl7Yz0idHJ1ZSI9PT1jPyEwOiJmYWxzZSI9PT1jPyExOiJudWxsIj09PWM/bnVsbDorYysiIj09PWM/K2M6dGEudGVzdChjKT9fLnBhcnNlSlNPTihjKTpjfWNhdGNoKGUpe31zYS5zZXQoYSxiLGMpfWVsc2UgYz12b2lkIDA7cmV0dXJuIGN9ZnVuY3Rpb24gaigpe3JldHVybiEwfWZ1bmN0aW9uIGsoKXtyZXR1cm4hMX1mdW5jdGlvbiBsKCl7dHJ5e3JldHVybiBaLmFjdGl2ZUVsZW1lbnR9Y2F0Y2goYSl7fX1mdW5jdGlvbiBtKGEsYil7cmV0dXJuIF8ubm9kZU5hbWUoYSwidGFibGUiKSYmXy5ub2RlTmFtZSgxMSE9PWIubm9kZVR5cGU/YjpiLmZpcnN0Q2hpbGQsInRyIik/YS5nZXRFbGVtZW50c0J5VGFnTmFtZSgidGJvZHkiKVswXXx8YS5hcHBlbmRDaGlsZChhLm93bmVyRG9jdW1lbnQuY3JlYXRlRWxlbWVudCgidGJvZHkiKSk6YX1mdW5jdGlvbiBuKGEpe3JldHVybiBhLnR5cGU9KG51bGwhPT1hLmdldEF0dHJpYnV0ZSgidHlwZSIpKSsiLyIrYS50eXBlLGF9ZnVuY3Rpb24gbyhhKXt2YXIgYj1LYS5leGVjKGEudHlwZSk7cmV0dXJuIGI/YS50eXBlPWJbMV06YS5yZW1vdmVBdHRyaWJ1dGUoInR5cGUiKSxhfWZ1bmN0aW9uIHAoYSxiKXtmb3IodmFyIGM9MCxkPWEubGVuZ3RoO2Q+YztjKyspcmEuc2V0KGFbY10sImdsb2JhbEV2YWwiLCFifHxyYS5nZXQoYltjXSwiZ2xvYmFsRXZhbCIpKX1mdW5jdGlvbiBxKGEsYil7dmFyIGMsZCxlLGYsZyxoLGksajtpZigxPT09Yi5ub2RlVHlwZSl7aWYocmEuaGFzRGF0YShhKSYmKGY9cmEuYWNjZXNzKGEpLGc9cmEuc2V0KGIsZiksaj1mLmV2ZW50cykpe2RlbGV0ZSBnLmhhbmRsZSxnLmV2ZW50cz17fTtmb3IoZSBpbiBqKWZvcihjPTAsZD1qW2VdLmxlbmd0aDtkPmM7YysrKV8uZXZlbnQuYWRkKGIsZSxqW2VdW2NdKX1zYS5oYXNEYXRhKGEpJiYoaD1zYS5hY2Nlc3MoYSksaT1fLmV4dGVuZCh7fSxoKSxzYS5zZXQoYixpKSl9fWZ1bmN0aW9uIHIoYSxiKXt2YXIgYz1hLmdldEVsZW1lbnRzQnlUYWdOYW1lP2EuZ2V0RWxlbWVudHNCeVRhZ05hbWUoYnx8IioiKTphLnF1ZXJ5U2VsZWN0b3JBbGw/YS5xdWVyeVNlbGVjdG9yQWxsKGJ8fCIqIik6W107cmV0dXJuIHZvaWQgMD09PWJ8fGImJl8ubm9kZU5hbWUoYSxiKT9fLm1lcmdlKFthXSxjKTpjfWZ1bmN0aW9uIHMoYSxiKXt2YXIgYz1iLm5vZGVOYW1lLnRvTG93ZXJDYXNlKCk7ImlucHV0Ij09PWMmJnlhLnRlc3QoYS50eXBlKT9iLmNoZWNrZWQ9YS5jaGVja2VkOigiaW5wdXQiPT09Y3x8InRleHRhcmVhIj09PWMpJiYoYi5kZWZhdWx0VmFsdWU9YS5kZWZhdWx0VmFsdWUpfWZ1bmN0aW9uIHQoYixjKXt2YXIgZCxlPV8oYy5jcmVhdGVFbGVtZW50KGIpKS5hcHBlbmRUbyhjLmJvZHkpLGY9YS5nZXREZWZhdWx0Q29tcHV0ZWRTdHlsZSYmKGQ9YS5nZXREZWZhdWx0Q29tcHV0ZWRTdHlsZShlWzBdKSk/ZC5kaXNwbGF5Ol8uY3NzKGVbMF0sImRpc3BsYXkiKTtyZXR1cm4gZS5kZXRhY2goKSxmfWZ1bmN0aW9uIHUoYSl7dmFyIGI9WixjPU9hW2FdO3JldHVybiBjfHwoYz10KGEsYiksIm5vbmUiIT09YyYmY3x8KE5hPShOYXx8XygiPGlmcmFtZSBmcmFtZWJvcmRlcj0nMCcgd2lkdGg9JzAnIGhlaWdodD0nMCcvPiIpKS5hcHBlbmRUbyhiLmRvY3VtZW50RWxlbWVudCksYj1OYVswXS5jb250ZW50RG9jdW1lbnQsYi53cml0ZSgpLGIuY2xvc2UoKSxjPXQoYSxiKSxOYS5kZXRhY2goKSksT2FbYV09YyksY31mdW5jdGlvbiB2KGEsYixjKXt2YXIgZCxlLGYsZyxoPWEuc3R5bGU7cmV0dXJuIGM9Y3x8UmEoYSksYyYmKGc9Yy5nZXRQcm9wZXJ0eVZhbHVlKGIpfHxjW2JdKSxjJiYoIiIhPT1nfHxfLmNvbnRhaW5zKGEub3duZXJEb2N1bWVudCxhKXx8KGc9Xy5zdHlsZShhLGIpKSxRYS50ZXN0KGcpJiZQYS50ZXN0KGIpJiYoZD1oLndpZHRoLGU9aC5taW5XaWR0aCxmPWgubWF4V2lkdGgsaC5taW5XaWR0aD1oLm1heFdpZHRoPWgud2lkdGg9ZyxnPWMud2lkdGgsaC53aWR0aD1kLGgubWluV2lkdGg9ZSxoLm1heFdpZHRoPWYpKSx2b2lkIDAhPT1nP2crIiI6Z31mdW5jdGlvbiB3KGEsYil7cmV0dXJue2dldDpmdW5jdGlvbigpe3JldHVybiBhKCk/dm9pZCBkZWxldGUgdGhpcy5nZXQ6KHRoaXMuZ2V0PWIpLmFwcGx5KHRoaXMsYXJndW1lbnRzKX19fWZ1bmN0aW9uIHgoYSxiKXtpZihiIGluIGEpcmV0dXJuIGI7Zm9yKHZhciBjPWJbMF0udG9VcHBlckNhc2UoKStiLnNsaWNlKDEpLGQ9YixlPVhhLmxlbmd0aDtlLS07KWlmKGI9WGFbZV0rYyxiIGluIGEpcmV0dXJuIGI7cmV0dXJuIGR9ZnVuY3Rpb24geShhLGIsYyl7dmFyIGQ9VGEuZXhlYyhiKTtyZXR1cm4gZD9NYXRoLm1heCgwLGRbMV0tKGN8fDApKSsoZFsyXXx8InB4Iik6Yn1mdW5jdGlvbiB6KGEsYixjLGQsZSl7Zm9yKHZhciBmPWM9PT0oZD8iYm9yZGVyIjoiY29udGVudCIpPzQ6IndpZHRoIj09PWI/MTowLGc9MDs0PmY7Zis9MikibWFyZ2luIj09PWMmJihnKz1fLmNzcyhhLGMrd2FbZl0sITAsZSkpLGQ/KCJjb250ZW50Ij09PWMmJihnLT1fLmNzcyhhLCJwYWRkaW5nIit3YVtmXSwhMCxlKSksIm1hcmdpbiIhPT1jJiYoZy09Xy5jc3MoYSwiYm9yZGVyIit3YVtmXSsiV2lkdGgiLCEwLGUpKSk6KGcrPV8uY3NzKGEsInBhZGRpbmciK3dhW2ZdLCEwLGUpLCJwYWRkaW5nIiE9PWMmJihnKz1fLmNzcyhhLCJib3JkZXIiK3dhW2ZdKyJXaWR0aCIsITAsZSkpKTtyZXR1cm4gZ31mdW5jdGlvbiBBKGEsYixjKXt2YXIgZD0hMCxlPSJ3aWR0aCI9PT1iP2Eub2Zmc2V0V2lkdGg6YS5vZmZzZXRIZWlnaHQsZj1SYShhKSxnPSJib3JkZXItYm94Ij09PV8uY3NzKGEsImJveFNpemluZyIsITEsZik7aWYoMD49ZXx8bnVsbD09ZSl7aWYoZT12KGEsYixmKSwoMD5lfHxudWxsPT1lKSYmKGU9YS5zdHlsZVtiXSksUWEudGVzdChlKSlyZXR1cm4gZTtkPWcmJihZLmJveFNpemluZ1JlbGlhYmxlKCl8fGU9PT1hLnN0eWxlW2JdKSxlPXBhcnNlRmxv